/**
 * Global Nudge Library (Round 30)
 * 200+ Gender-Aware, Hilarious, and Actionable Messages
 */

export const GLOBAL_NUDGES: { male: string[], female: string[] } = {
    male: [
        // Morning (0-40)
        "Wake up, Beast! 🦁 Your biceps are already shrinking. Log that breakfast!",
        "Morning, Champ! ☕ Coffee is good, but protein is better. Show me the logs.",
        "Today's mission: Don't be a average. Start with a high-protein meal, King.",
        "Sun's up, guns up! 💪 Log your first meal or I'm telling your PT you've retired.",
        "Early bird gets the gains. 🪱 Log something with a pulse right now!",
        "Your muscles are currently in 'emergency power' mode. Feed them, bro!",
        "Don't let your metabolism sleep in. Log that morning fuel!",
        "Is this a fast or did you forget you're a warrior? Log breakfast!",
        "Success starts with a log. 📝 What are we eating today, boss?",
        "Rise and grind! ⚡ Your protein goal is waiting. Don't leave it hanging.",
        "Your six-pack is hiding behind a lack of logs. Find it!",
        "Legend says those who log first thing get 20% more gains. It's me, I'm the legend.",
        "Fuel the machine. 🦾 Log your morning intake before the day eats you.",
        "Good morning, Gladiator! 🛡️ Grab some eggs and log it. No excuses.",
        "Your biceps just sent me a DM. They're starving. Log something!",
        "A king doesn't skip breakfast. 👑 Log your royal meal now.",
        "Today is a great day to crush your goals. Start with a solid log!",
        "Your willpower is a muscle. Train it by logging your first meal.",
        "Stop scrolling and start logging! 📱 Gains are waiting.",
        "Morning check-in: Are we being a beast today or a couch potato? Log!",
        "Your future self just called. He says thanks for logging today.",
        "One log at a time, bro. Let's get that morning streak started.",
        "The gym is calling, but your kitchen is the real MVP. Log breakfast!",
        "Don't be a 'tomorrow' guy. Be a 'logged it at 8 AM' guy.",
        "Your energy levels are looking for a spark. Log some fuel!",
        "A lion doesn't lose sleep over the opinion of sheep... or over skipped logs. Log!",
        "Be the guy your dog thinks you are. Log that healthy breakfast!",
        "Your muscles are like a high-end car. Don't run them on empty. Log!",
        "Victory is earned in the kitchen. 🍳 Log your first win of the day.",
        "Is that a coffee or a meal? ☕ If it's just coffee, we have a problem. Log!",
        "Yesterday's effort counts for nothing if you skip today. Log now!",
        "Your protein goal isn't going to hit itself. Get to work!",
        "Log like a boss. 💪 Your stats are waiting for an update.",
        "Consistency is the secret sauce. 🍯 Start the day with a log.",
        "Your body is a temple, not a storage unit. Log what goes in!",
        "Don't let the day get ahead of you. Log your morning intake now.",
        "A warrior prepares. ⚔️ Log your fuel and conquer the day.",
        "Your biceps are 70% water and 100% waiting for you to log protein.",
        "Imagine your goals. Now log the food that gets you there!",
        "Early morning gains are the sweetest. 🍬 Log your breakfast, King.",

        // Midday (41-80)
        "Lunchtime, Legend! 🥗 40g of protein or we're not talking. Log it!",
        "Midday check: Are you fueling or just 'existing'? Log that lunch.",
        "Stop working, start eating! 🍖 Your gains need mid-day support.",
        "Your metabolism is bored. Give it something to do. Log lunch!",
        "Don't let the afternoon slump win. Fuel up and log it!",
        "Is that a salad or a snack? 🥗 If it's a meal, log it like a man.",
        "Halfway through the day! 🌓 How's that protein looking? Log!",
        "Your muscles are whispering... they want chicken. 🍗 Log it!",
        "Don't be the guy who 'forgets to eat'. Log your lunch now.",
        "Performance requires fuel. 🏎️ Log your mid-day intake, champ.",
        "Your streak is watching you. 👁️ Keep it alive with a lunch log.",
        "Mid-day motivation: You're doing great, but you'd be doing better with logs!",
        "A beast needs his fuel. 🥩 Log those midday calories right now.",
        "Don't let your energy crash at 3 PM. Log a solid lunch!",
        "Your goals don't take a lunch break. 🥪 Log your meal!",
        "Is it lunchtime or just 'staring at the fridge' time? Log something!",
        "Your biceps called again. They're still hungry. Feed them!",
        "Lunch is the bridge to your afternoon PRs. 🌉 Log it!",
        "Consistency check! 📉 Are we still on track? Log your lunch.",
        "Don't let a busy day be an excuse for a weak log. Log lunch!",
        "Your body is craving nutrients, not just caffeine. ☕ Log real food!",
        "Midday status: Beast mode or sleep mode? Log to stay in beast mode.",
        "Every log is a step closer to that goal weight. Log lunch!",
        "Don't settle for 'good enough'. Log 'great' fuel today.",
        "Your muscles are currently holding a protest. 🪧 End it with a lunch log!",
        "Imagine the gains. Now log the lunch that builds them.",
        "Stop thinking about the gym and start thinking about your plate. Log!",
        "A warrior eats to win. 🛡️ Log your mid-day victory.",
        "Lunch is served! 🍽️ Don't forget the most important part: The LOG.",
        "Your energy is your currency. 💰 Spend it wisely with a good lunch. Log!",
        "Mid-day report: Protein is looking lonely. Add some friends. Log!",
        "Don't just eat, log. It's the law of the jungle. 🦁",
        "Your discipline is showing. Keep it up with a lunch log.",
        "Is that lunch or just a series of snacks? 🥨 Log it properly!",
        "Your future self is flexing in the mirror because you logged lunch.",
        "Midday reminder: You're 100% in control of these gains. Log!",
        "Don't let your stomach do the talking. Log your brain's choice!",
        "Lunchtime = Logtime. 🕒 It's a simple equation, bro.",
        "Your goals are getting closer. Don't slow down now. Log lunch!",
        "A beast doesn't graze. He eats with purpose. Log it!",

        // Afternoon (81-120)
        "Afternoon slump? 📉 Or protein deficit? Log a snack, King.",
        "It's 4 PM. Your biceps are currently crying. Grab a shake!",
        "Don't let the day end without hitting that goal. Log something!",
        "Is your water bottle empty? 💧 Fill it and log it, hydrated king.",
        "Afternoon check-in: 75% of the day done. How's the log?",
        "Snack time! 🍎 Make it high protein and log it like a pro.",
        "Your energy is flagging. 🚩 Log some fuel to finish strong.",
        "Don't wait for dinner to catch up. Log an afternoon snack.",
        "Your muscles have a 5 PM appointment with some protein. Log it!",
        "Is this a plateau or a 'forgot to log afternoon' situation? Log!",
        "Consistency is easy when you log every snack. Try it now!",
        "Your future self thanks you for that 4 PM protein hit. Log it!",
        "Afternoon reminder: You're a beast, not a bystander. Log!",
        "Don't let the evening hunger win. Prep with a logged snack.",
        "Your biceps are 90% water and 10% 'why haven't you logged yet?'.",
        "It's nearly 5! 🕔 How many steps have we logged? Keep moving!",
        "Log a glass of water. 🌊 Your brain needs it to stay sharp.",
        "Afternoon vibes: Focus and Fuel. 🎯 Log your current intake.",
        "Don't just survive the afternoon, thrive in it. Log a snack!",
        "Your streak is looking for one more log today. Give it what it wants.",
        "Is that a snack or a small meal? 🥨 Either way, log it, champ.",
        "Afternoon status: Legend in the making. 🏆 Keep logging!",
        "Don't let your afternoon be 'unaccounted for'. Log it!",
        "Your goals are watching. 👁️ Show them you're committed. Log!",
        "A little afternoon protein goes a long way. 🛤️ Log it now.",
        "It's 4 PM! 🕓 Do you know where your macros are? Log them!",
        "Don't let the sun go down on a weak log. Log something now!",
        "Afternoon check: Are we hitting the target? 🎯 Adjust and log.",
        "Your muscles are currently in 'maintenance mode'. Upgrade them!",
        "Is it tea time or protein time? 🍵 (Hint: It's protein). Log!",
        "Afternoon motivation: The gym is coming up. Pre-fuel and log.",
        "Don't let your focus slip. Log a healthy afternoon choice.",
        "Your streak is a badge of honor. 🏅 Keep it shining. Log!",
        "Afternoon report: We're so close to the goal! Log a snack.",
        "Be the guy who never misses a log. 👊 Consistency is king.",
        "Is that an afternoon slump or just a lack of data? Log!",
        "Your body is a high-performance engine. 🏎️ Log the fuel.",
        "Afternoon vibes: Calm, Collected, and Logged. 😌",
        "Don't wait for the 'perfect' moment. Log what you just ate!",
        "Log your afternoon water. 💧 Hydration = Performance.",

        // Evening (121-160)
        "Dinner time, Boss! 🍽️ Log your biggest win of the day.",
        "Evening check-in: Did we hit the protein goal? 🥓 Log dinner!",
        "Success is a dish best served... logged. Log your dinner!",
        "Don't go to bed with a 'pending' log. Finish strong, King.",
        "Your muscles grow while you sleep. 💤 Give them fuel tonight!",
        "Is that dinner or a feast? 🍗 Whichever it is, log it, legend.",
        "Evening status: Goal Crushed or Goal Pending? Log now!",
        "Don't let the couch win yet. Log your final meal first.",
        "Your streak protection is active. 🛡️ Log dinner to keep it safe.",
        "Consistency is the final boss. 👾 Defeat it with an evening log!",
        "Dinner is the foundation of tomorrow's gains. 🏗️ Log it!",
        "Evening reminder: You're officially a beast if you log this.",
        "Don't let the day end on a 0. Log that evening intake!",
        "Your future self is already stronger because of tonight's log.",
        "Is it dinner time or 'scrolling' time? 📱 Switch and log!",
        "Your biceps are currently reviewing today's data. Impress them!",
        "Log your dinner and secure the 100% completion badge. 🎖️",
        "Evening vibes: Accomplished and Accountable. 🤝 Log now!",
        "Don't let a late meal be an unlogged meal. Log it, champ.",
        "Your goals don't sleep. 😴 Neither should your logging. Log dinner!",
        "A warrior finishes what he starts. ⚔️ Log your final meal.",
        "Evening report: We're 95% there! Log dinner to finish the job.",
        "Don't be the guy who 'forgets the last log'. Log dinner!",
        "Your protein goal is begging for one last hit. 🥩 Log it!",
        "Evening status: Elite level. 🌟 Keep it up with a dinner log.",
        "Is that a cheat meal? 🍔 Log it anyway! Honesty builds armor.",
        "Your discipline is your superpower. 🦸‍♂️ Log your evening fuel.",
        "Don't let the day fade away without a final log. Log dinner!",
        "Evening motivation: Tomorrow starts tonight. Log your dinner.",
        "Is dinner done? 🍽️ Then the log should be too! Do it now.",
        "Your streak is a story of your commitment. 📖 Write tonight's chapter.",
        "Evening vibes: Relaxed but Diligent. 🧐 Log your intake.",
        "Don't let your efforts go unrecorded. 📝 Log your dinner, King.",
        "Evening status: Goal in sight! 🔭 Log dinner to reach it.",
        "A beast treats his body with respect. 🦁 Log your final fuel.",
        "Is it bedtime? 🛌 Wait! Did you log dinner? Do it now!",
        "Your future self is proud of your consistency. Log dinner.",
        "Evening reminder: You're 100% committed. Prove it. Log!",
        "Don't leave your macros guessing. Log your dinner, boss.",
        "Success is habitual. 🔁 Log your dinner to keep the habit alive.",

        // Night (161-200)
        "Late night snack? 🍪 Log it, sneaky beast. I see you!",
        "Thinking of a midnight raid? 🥪 Log it before you eat it!",
        "Night check: Is the day fully logged? 📝 Don't leave a gap.",
        "Sleep is for recovery. Logging is for results. 💤 Log now!",
        "Is your streak safe? 🛡️ Check your logs before you hit the hay.",
        "Late night protein shake? 🥤 Great choice. Now log it!",
        "Don't let your night be 'data-free'. Log those last bites.",
        "Your muscles are prepping for the overnight rebuild. Fuel them!",
        "Is that a midnight snack or a dream? 🌙 Whichever, log it!",
        "Night vibes: Secure the gains. 🔒 Log your final stats.",
        "Don't go to sleep without checking your water. 💧 Log it!",
        "Late night check-in: 100% logged? 💯 Victory is yours.",
        "Your streak is a fragile flame. 🔥 Protect it with a final log.",
        "Night status: Champion in progress. 🏆 Log your day's end.",
        "Is the kitchen finally closed? 🚪 Then the app should be too. Log!",
        "Tomorrow's mirror will reflect tonight's discipline. Log!",
        "Night reminder: Consistency is the only way. Log your final bit.",
        "Don't let the day end on a 'maybe'. Log your actuals!",
        "Your biceps are thankful for the 24/7 accountability. Log!",
        "Night vibes: Done and Dusted. ✨ Log your final check-in.",
        "Is everything in? 📥 Check your logs one last time, champ.",
        "Late night honesty: Log that snack! 🍕 We don't judge, we log.",
        "Your goals are getting closer while you sleep. 😴 Stay logged.",
        "Night status: On track. 🚂 Don't derail now. Log the last bits.",
        "Don't let your hard work be forgotten. 💭 Log your night intake.",
        "Is it 10 PM? 🕙 Time for a final log check. Are we done?",
        "Night motivation: You're winning the day. Finish with a log.",
        "Your streak is a testament to your grit. 💪 Keep it growing.",
        "Night vibes: Focused and Finished. 🏁 Log your final entry.",
        "Don't sleep on your goals. 🛌 Log your final intake now!",
        "Is your water bottle by the bed? 💧 Log the last glass.",
        "Night status: Goal-Getter. 🎯 See you in the morning. Log!",
        "Late night wisdom: A log in time saves the gains. Log!",
        "Your future self is sleeping soundly because you logged. 💤",
        "Night reminder: You're the captain of this ship. ⚓ Log!",
        "Is the day finished? 🌑 Then the story should be too. Log.",
        "Night vibes: Accountability check. 🧐 Are we 100% logged?",
        "Don't let the day end without a final 'Good Job' to yourself. Log!",
        "Night status: Legend status unlocked. 🔓 Log your final entry.",
        "Sleep well, King. 👑 Your logs are safe. See you tomorrow!"
    ],
    female: [
        // Morning (0-40)
        "Morning, Queen! 👑 Your glow needs fuel. Log your breakfast!",
        "Rise and shine, Goddess! ✨ Protein for breakfast = Goddess energy all day.",
        "Your beauty starts from within. 🥗 Log your first healthy choice!",
        "Wake up and win, Lady! ☕ Log that morning fuel and conquer.",
        "Don't skip the most important log of the day. 📝 Morning check-in!",
        "Your glow is a habit. 💄 Keep it up with a healthy breakfast log.",
        "Energy is your best accessory. ⚡ Log your morning fuel, Queen.",
        "Is it a coffee morning or a protein morning? ☕ (Log both!)",
        "Morning check-in: Are we being a powerhouse today? 💪 Log!",
        "Your future self is thanking you for this logged breakfast. ✨",
        "Good morning, Sunshine! ☀️ Log something that makes you feel amazing.",
        "Start the day with a win. 🍳 Log your breakfast right now!",
        "Your radiance is waiting for some nutrients. Log your breakfast!",
        "Don't just dream of your goals, log them into reality. 🌈",
        "Morning vibes: Focused, Fierce, and Fueled. 🎯 Log now!",
        "Your body is a temple, treat it to a logged breakfast. 🕍",
        "Is that a green smoothie? 🥤 Show off and log it, girl!",
        "Today's mantra: Fuel, Focus, Flourish. 🌸 Log your start.",
        "Morning reminder: You're a goddess in progress. 🏛️ Log!",
        "Success is built one log at a time. Start your morning streak!",
        "Don't be a 'later' person. Be a 'logged it at 8 AM' Queen. 👑",
        "Your energy levels are looking for a spark. Log some fuel!",
        "A healthy start is the best foundation. 🏗️ Log your breakfast.",
        "Is your water bottle ready? 💧 Log your first glass too!",
        "Morning check-in: How's your heart? How's your log? ❤️📝",
        "Your goals are beautiful. Log the food that helps you reach them.",
        "Don't let the day rush you. Take a moment to log your breakfast.",
        "Morning vibes: Calm and Committed. 🧘‍♀️ Log your fuel.",
        "Is that oatmeal I smell? 🥣 It looks better in the log! Do it.",
        "Your radiance is a reflection of your choices. Log a good one!",
        "Morning status: Goal-Getter. 🎯 Log your first step today.",
        "A goddess doesn't skip meals. 🍇 Log your morning feast.",
        "Success is a habit, not an event. 🔁 Log your breakfast habit.",
        "Don't let your metabolism miss the memo. Log morning food!",
        "Your future self is smiling because you're logging today. 😊",
        "Morning reminder: You're powerful and logged. 💪📝",
        "Is it breakfast time or 'scrolling' time? 📱 Switch and log, Queen.",
        "Your body is a masterpiece. 🎨 Fuel it with logged nutrients.",
        "Morning vibes: Empowered and Accountable. 🤝 Log now!",
        "Don't wait for the mid-day slump. Start strong with a morning log.",

        // Midday (41-80)
        "Lunchtime, Goddess! 🥗 Protein is the secret to that glow. Log it!",
        "Midday check: Are you fueling or just 'getting by'? Log lunch!",
        "Queen, it's 1 PM! 🕐 Time to refuel and log your midday win.",
        "Is that a salad or a power bowl? 🥙 Either way, log it, girl!",
        "Don't let the afternoon be a 'blah'. Log a great lunch now.",
        "Performance requires nutrients. 🚀 Log your mid-day intake, Lady.",
        "Your streak is watching you with love. 💖 Keep it alive with a log.",
        "Mid-day motivation: You're crushing it! Log your fuel to stay on top.",
        "A powerhouse lady needs her fuel. 🥘 Log those midday calories.",
        "Don't let your energy crash. Log a solid, protein-packed lunch!",
        "Your goals don't take a lunch break. 🥪 Log your meal, Queen.",
        "Is it lunchtime or just 'thinking about food' time? Log something!",
        "Your radiance is building with every healthy choice. 🌟 Log it!",
        "Lunch is the bridge to your afternoon brilliance. 🌉 Log it!",
        "Consistency check! 📉 Still on track? Log your lunch fuel.",
        "Don't let a busy day dim your discipline. Log lunch, Goddess!",
        "Your body wants vitamins, not just caffeine. ☕ Log real food!",
        "Midday status: Goal-Crusher or Just Busy? Log to be a crusher.",
        "Every log is a wink at your future self. 😉 Log lunch now!",
        "Don't settle for 'good enough'. Log 'great' fuel today.",
        "Your muscles are asking for a lunch log. 🥗 Don't keep them waiting!",
        "Imagine the energy. Now log the lunch that provides it.",
        "Stop thinking about the gym and start thinking about your plate. Log!",
        "A lady eats to win her day. 🛡️ Log your mid-day victory.",
        "Lunch is served! 🍽️ Don't forget the sparkle: The LOG.",
        "Your energy is your magic. ✨ Protect it with a good lunch. Log!",
        "Mid-day report: Protein is looking lonely. Add some friends. Log!",
        "Don't just eat, log. It's the secret to the glow. 💖",
        "Your discipline is your charm. ✨ Keep it up with a lunch log.",
        "Is that lunch or just a series of snacks? 🥨 Log it properly!",
        "Your future self is glowing in the mirror because you logged lunch.",
        "Midday reminder: You're 100% in control of this journey. Log!",
        "Don't let your cravings do the talking. Log your brain's choice!",
        "Lunchtime = Logtime. 🕒 It's a simple equation, Queen.",
        "Your goals are getting closer. Don't slow down now. Log lunch!",
        "A goddess doesn't graze. She fuels with purpose. Log it!",

        // Afternoon (81-120)
        "Afternoon slump? 📉 Or hydration gap? Drink some H2O and log!",
        "It's 4 PM. Your future self wants some protein. Grab a snack!",
        "Don't let the day end without hitting that goal. Log something!",
        "Is your water bottle empty? 💧 Hydration = Glowing Skin. Log!",
        "Afternoon check-in: 75% of the day done. How's the log, Lady?",
        "Snack time! 🍎 Make it high protein and log it like a goddess.",
        "Your energy is flagging. 🚩 Log some fuel to finish strong, Queen.",
        "Don't wait for dinner to catch up. Log an afternoon snack.",
        "Your glow has a 5 PM appointment with some nutrients. Log it!",
        "Is this a plateau or a 'forgot to log afternoon' situation? Log!",
        "Consistency is a superpower. 🦸‍♀️ Try logging your snack now!",
        "Your future self thanks you for that 4 PM protein hit. Log it!",
        "Afternoon reminder: You're a goddess, not a bystander. Log!",
        "Don't let the evening hunger win. Prep with a logged snack.",
        "Your radiance is 70% water and 10% 'why haven't you logged yet?'.",
        "It's nearly 5! 🕔 How many steps have we logged? Keep moving!",
        "Log a glass of water. 🌊 Your brain needs it to stay sharp, Queen.",
        "Afternoon vibes: Grace and Grit. 🎯 Log your current intake.",
        "Don't just survive the afternoon, thrive in it. Log a snack!",
        "Your streak is looking for one more log today. Give it what it wants.",
        "Is that a snack or a treat? 🍓 Either way, log it, Goddess.",
        "Afternoon status: Legend in the making. 🏆 Keep logging!",
        "Don't let your afternoon be 'unaccounted for'. Log it, Lady!",
        "Your goals are watching. 👁️ Show them you're committed. Log!",
        "A little afternoon protein goes a long way. 🛤️ Log it now.",
        "It's 4 PM! 🕓 Do you know where your macros are? Log them!",
        "Don't let the sun go down on a weak log. Log something, Queen!",
        "Afternoon check: Are we hitting the target? 🎯 Adjust and log.",
        "Your radiance is currently in 'recharge mode'. Fuel it!",
        "Is it tea time or protein time? 🍵 (Hint: It's protein). Log!",
        "Afternoon motivation: The workout is coming. Pre-fuel and log.",
        "Don't let your focus slip. Log a healthy afternoon choice.",
        "Your streak is a necklace of commitment. 📿 Keep it shining. Log!",
        "Afternoon report: We're so close to the goal! Log a snack.",
        "Be the lady who never misses a log. 👊 Consistency is queenly.",
        "Is that an afternoon slump or just a lack of data? Log!",
        "Your body is a high-performance temple. 🏛️ Log the fuel.",
        "Afternoon vibes: Calm, Collected, and Logged. 😌",
        "Don't wait for the 'perfect' moment. Log what you just ate!",
        "Log your afternoon water. 💧 Hydration = Performance.",

        // Evening (121-160)
        "Dinner time, Queen! 🍽️ Log your biggest win of the day.",
        "Evening check-in: Did we hit the protein goal? 🍗 Log dinner!",
        "Success is a dish best served... logged. Log your dinner!",
        "Don't go to bed with a 'pending' log. Finish strong, Lady.",
        "Your body glows while you sleep. 💤 Give it fuel tonight!",
        "Is that dinner or a celebration? 🥗 Whichever, log it, Goddess.",
        "Evening status: Goal Crushed or Goal Pending? Log now!",
        "Don't let the couch win yet. Log your final meal first.",
        "Your streak protection is active. 🛡️ Log dinner to keep it safe.",
        "Consistency is the final boss. 👾 Defeat it with an evening log!",
        "Dinner is the foundation of tomorrow's glow. 🏗️ Log it!",
        "Evening reminder: You're officially a powerhouse if you log this.",
        "Don't let the day end on a 0. Log that evening intake!",
        "Your future self is already stronger because of tonight's log.",
        "Is it dinner time or 'scrolling' time? 📱 Switch and log, Queen!",
        "Your radiance is currently reviewing today's data. Impress it!",
        "Log your dinner and secure the 100% completion badge. 🎖️",
        "Evening vibes: Accomplished and Accountable. 🤝 Log now!",
        "Don't let a late meal be an unlogged meal. Log it, Goddess.",
        "Your goals don't sleep. 😴 Neither should your logging. Log dinner!",
        "A lady finishes what she starts. 🛡️ Log your final meal.",
        "Evening report: We're 95% there! Log dinner to finish the job.",
        "Don't be the one who 'forgets the last log'. Log dinner!",
        "Your protein goal is begging for one last hit. 🍗 Log it!",
        "Evening status: Elite level. 🌟 Keep it up with a dinner log.",
        "Is that a treat? 🍰 Log it anyway! Honesty builds trust with yourself.",
        "Your discipline is your superpower. 🦸‍♂️ Log your evening fuel.",
        "Don't let the day fade away without a final log. Log dinner!",
        "Evening motivation: Tomorrow starts tonight. Log your dinner.",
        "Is dinner done? 🍽️ Then the log should be too! Do it now, Queen.",
        "Your streak is a story of your commitment. 📖 Write tonight's chapter.",
        "Evening vibes: Relaxed but Diligent. 🧐 Log your intake.",
        "Don't let your efforts go unrecorded. 📝 Log your dinner, Lady.",
        "Evening status: Goal in sight! 🔭 Log dinner to reach it.",
        "A goddess treats her body with respect. 🏛️ Log your final fuel.",
        "Is it bedtime? 🛌 Wait! Did you log dinner? Do it now!",
        "Your future self is proud of your consistency. Log dinner.",
        "Evening reminder: You're 100% committed. Prove it. Log!",
        "Don't leave your macros guessing. Log your dinner, Queen.",
        "Success is habitual. 🔁 Log your dinner to keep the habit alive.",

        // Night (161-200)
        "Late night snack? 🍓 Log it, sneaky Goddess. I see you!",
        "Thinking of a midnight treat? 🍰 Log it before you eat it!",
        "Night check: Is the day fully logged? 📝 Don't leave a gap.",
        "Sleep is for recovery. Logging is for results. 💤 Log now!",
        "Is your streak safe? 🛡️ Check your status before you drift off.",
        "Late night protein shake? 🥤 Great choice. Now log it, Queen.",
        "Don't let your night be 'data-free'. Log those last bites.",
        "Your body is prepping for the overnight glow. Fuel it!",
        "Is that a midnight snack or a dream? 🌙 Whichever, log it!",
        "Night vibes: Secure the gains. 🔒 Log your final stats.",
        "Don't go to sleep without checking your water. 💧 Log it!",
        "Late night check-in: 100% logged? 💯 Victory is yours, Goddess.",
        "Your streak is a fragile flame. 🔥 Protect it with a final log.",
        "Night status: Champion in progress. 🏆 Log your day's end.",
        "Is the kitchen finally closed? 🚪 Then the app should be too. Log!",
        "Tomorrow's mirror will reflect tonight's discipline. Log!",
        "Night reminder: Consistency is the only way. Log your final bit.",
        "Don't let the day end on a 'maybe'. Log your actuals, Queen.",
        "Your radiance is thankful for the 24/7 accountability. Log!",
        "Night vibes: Done and Dusted. ✨ Log your final check-in.",
        "Is everything in? 📥 Check your logs one last time, Lady.",
        "Late night honesty: Log that snack! 🍕 We don't judge, we log.",
        "Your goals are getting closer while you sleep. 😴 Stay logged.",
        "Night status: On track. 🚂 Don't derail now. Log the last bits.",
        "Don't let your hard work be forgotten. 💭 Log your night intake.",
        "Is it 10 PM? 🕙 Time for a final log check. Are we done, Queen?",
        "Night motivation: You're winning the day. Finish with a log.",
        "Your streak is a testament to your grit. 💪 Keep it growing, Lady.",
        "Night vibes: Focused and Finished. 🏁 Log your final entry.",
        "Don't sleep on your goals. 🛌 Log your final intake now!",
        "Is your water bottle by the bed? 💧 Log the last glass.",
        "Night status: Goal-Getter. 🎯 See you in the morning. Log!",
        "Late night wisdom: A log in time saves the gains. Log, Queen!",
        "Your future self is sleeping soundly because you logged. 💤",
        "Night reminder: You're the captain of this ship. ⚓ Log!",
        "Is the day finished? 🌑 Then the story should be too. Log.",
        "Night vibes: Accountability check. 🧐 Are we 100% logged?",
        "Don't let the day end without a final 'Good Job' to yourself. Log!",
        "Night status: Goddess status unlocked. 🔓 Log your final entry.",
        "Sleep well, Queen. 👑 Your logs are safe. See you tomorrow!"
    ]
};
